name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install Deps
      run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libtidy-dev libjansson-dev check
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --enable-werror
    - name: make
      run: make
    - name: Start Docker SMM
      run: |
        docker compose -f tests/docker-compose.yml up -d smm db
        ./tests/provision.sh
    - name: Run Tests in Docker
      run: docker compose -f tests/docker-compose.yml run tester
    - name: make distcheck
      run: make distcheck
